name: wizard-backend
services:
  mongodb:
    container_name: mongo-db
    image: mongo
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      # named volumes
      - mongodb-volume:/data/db
      - mongoconfig:/data/configdb
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@mongodb:${DB_PORT}

volumes:
  mongodb-volume:
  mongoconfig:
