name: wizard-backend
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      # named volumes
      - mongodb-volume:/data/db
      - mongoconfig:/data/configdb


volumes:
  mongodb-volume:
  mongoconfig: